version: "3.9"

services:
  api:
    build: .
    container_name: agendify_api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: agendify_db
    environment:
      POSTGRES_DB: agendify
      POSTGRES_USER: root_agendify
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
